### ISSUE TITLE
Import of next/router throws error in nextra-theme-docs

### ISSUE THREAD

**Issue by barnagoz** [visulima/visulima#227]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/visulima/visulima/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/visulima/visulima/blob/main/.github/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/visulima/visulima/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Visulima issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/visulima/visulima/discussions) or join our [Discord Chat Server](https://chat.visulima.com).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

Hey!
I have a nextra project and I successfully found your theme for it, which I really like. Currently my site is accessible at [info.e5vosdo.hu](info.e5vosdo.hu). When I try to install the theme (as the documentation shows me, except I just edit some files and don't create them) I get the following error:
```
⨯ Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/barnabasgoz/Development/do/web/node_modules/next/router' imported from /Users/barnabasgoz/Development/do/web/node_modules/@visulima/nextra-theme-docs/dist/index.mjs
Did you mean to import next/router.js?
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:226:11)
    at moduleResolve (node:internal/modules/esm/resolve:839:10)
    at defaultResolve (node:internal/modules/esm/resolve:1069:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:307:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:156:32)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  page: '/'
}
```

### Minimal reproduction code

1. Clone the nextra docs template ([https://github.com/shuding/nextra-docs-template](https://github.com/shuding/nextra-docs-template)
2. Install the deps your project needs
`npm i next react react-dom nextra @visulima/nextra-theme-docs`
3. Install other deps
`npm i`
4. Edit next.config.js
```
const withNextra = require("nextra")({
  theme: "@visulima/nextra-theme-docs",
  themeConfig: "./theme.config.tsx",
});

module.exports = withNextra();
```
5. Run development server 

### Additional Context

![Képernyőfotó 2023-10-21 - 13 25 49](https://github.com/visulima/visulima/assets/82385832/deac4c25-f185-4735-9dd5-78dc0e6f0bee)

### Environment Info

```shell
System:
    OS: macOS 12.6.8
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 1.50 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 20.1.0 - /usr/local/bin/node
    Yarn: 3.2.4 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.6.1 - /usr/local/bin/pnpm
Browsers:
    Safari: 16.6
npmPackages:
    @visulima/nextra-theme-docs: ^4.0.3 => 4.0.3
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

**Comment by prisis** [comment]
Hey @barnagoz, the newest version should fix all your issues :)
