### ISSUE TITLE
Using @visulima/jsdoc-open-api with deno?

### ISSUE THREAD

**Issue by mahdiyari** [visulima/visulima#480]
Would it be possible to somehow use `@visulima/jsdoc-open-api` with Deno? I couldn't figure it out.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/visulima) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/visulima/visulima/issues/480">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/visulima/visulima/issues/480/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/visulima/visulima/issues/480/pledge.svg">
</picture>
</a>

**Comment by prisis** [comment]
Hey 👋, it should be possible to use it with deno.

deno 2 added support for node packages, so it should work somehow the same, you need to install all 3 packages if you using the cli and then call the cli command
